import Head from "next/head";
import styles from "/styles/Home.module.css";
import { LoginFrom } from "@/components";

export default function Home() {
  return (
    <div className={styles.main}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="tourist" content="nextjs,tourist guide" />
        <link rel="icon" href="/favcion.ico" />
      </Head>

      <LoginFrom />
    </div>
  );
}
